### PR TITLE
downgrade to 1.20.1

### PR DESCRIPTION
**Pull request by RemagOfficial**
downgraded the mod to 1.20.1, item models, blockstates and lang datagen are currently broken and i dont really have the skill to fix those as ive never done datagen

### CODE REVIEW

**Comment by RemagOfficial** [comment]
youll want to make a branch for this if you want to merge it

**Comment by DriHut** [comment]
I will check it next week quite busy atm ^^ but so far look like it should work just fine (btw generator is just done using the gradle task so it should work).

**Comment by RemagOfficial** [comment]
ah it does work, should have read the wiki better lmao

**Comment by RemagOfficial** [comment]
also the github read me says it adds pressure plates and buttons but it doesnt

**Comment by DriHut** [comment]
no it doesn't it says shapes that are planned to be added ^^

**Review by DriHut — APPROVED** [review]
all good all funtionalities work

**Pull request merged**
